@startuml reward

participant MicroCity as oracle
actor Guest as guest
participant Activity as activity

oracle -> guest : "suggest"
activate guest

alt follow suggestion
guest -> guest : "take the suggestion"
guest -> activity : "benefits from"
activate activity
return "reward"
activity -> oracle : "inform"
else ignore suggestion
guest -> guest : "ignore suggestion"
end
return


@enduml